# Linear regression
T0 = 5
T1 = 50
DEFAULT_INITIAL_ETA = T0 / T1

# SGD ANALYSIS
ANALYSIS_DATA_SIZE = 20
ANALYSIS_DEGREE = 5
ANALYSIS_TEST_SIZE = 0.2

EPOCH_STEP_SIZE = 20
HIGHEST_EPOCH = 120

N_MINI_BATCH_START = 2
N_MINI_BATCH_END = 120
N_MINI_BATCH_STEP_SIZE = 30

NUMBER_OF_ETAS = 4
SMALLEST_ETA = 0.1
LARGEST_ETA = 3

NUMBER_OF_LAMBDAS = 4
SMALLEST_LAMBDA = -7
LARGEST_LAMBDA = -1

EPOCHS = [1] + list(
    range(EPOCH_STEP_SIZE, HIGHEST_EPOCH + EPOCH_STEP_SIZE, EPOCH_STEP_SIZE)
)
MINIBATCHES = list(range(N_MINI_BATCH_START, N_MINI_BATCH_END, N_MINI_BATCH_STEP_SIZE))
