# Linear regression
t0 = 5
t1 = 50

# SGD ANALYSIS
EPOCH_STEP_SIZE = 10
HIGHEST_EPOCH = 50  # at least 120

N_MINI_BATCH_START = 2
N_MINI_BATCH_END = 120
N_MINI_BATCH_STEP_SIZE = 30  # maybe 16

NUMBER_OF_ETAS = 10  # increase for real run
SMALLEST_ETA = 0.001
BIGGEST_ETA = 3
